title: 'Maximilian Rüsch'
baseURL: 'https://maximilianruesch.de/'
languageCode: 'en-GB'

theme: "PaperMod"
params:
  ShowBreadCrumbs: true

  author: "Maximilian Rüsch"
  description: "Personal homepage displaying my projects and other achievements"
  keywords:
    - maximilianruesch
    - maximilianrüsch
    - maxruesch
    - maxrüsch
    - max
    - ruesch
    - rüsch
    - sector lengths

  assets:
    favicon: '/icons/favicon.ico'
    favicon16x16: '/icons/favicon-16x16.png'
    favicon32x32: '/icons/favicon-16x16.png'
    apple_touch_icon: '/icons/apple-touch-icon.png'

  profileMode:
    enabled: true
    title: "Maximilian Rüsch" # optional default will be site title
    subtitle: "<subtitle>"
    imageUrl: "max.jpg"
    imageTitle: me # optional
    imageWidth: 300 # custom size
    imageHeight: " " # custom size
    buttons:
      - name: Science
        url: "/scientific"
        draft: true

  socialIcons: # optional
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/maximilianruesch/"
    - name: "GitHub"
      url: "https://github.com/maximilianruesch"

menu:
  main:
    - identifier: scientific
      name: Scientific Projects
      url: /scientific
      weight: 10
    - identifier: projects
      name: Personal Projects
      url: /projects
      weight: 20